### ISSUE TITLE
Removal of /etc/network/interfaces

### ISSUE THREAD

**Issue by jessr92** [geerlingguy/diet-raspbian#6]
Is the removal of the file /etc/network/interfaces deliberate?

It causes more problems than it is worth to be honest. I've found in all cases I've had to re-add the contents back in (eth0 for DHCP and the lo interface to allow mysql-server to restart) but I can't work out what part of the YML files is causing the removal.

**Comment by geerlingguy** [comment]
@gordon1992 - You know, I just realized this is happening myself, when I was rebuilding `drupal-pi` and my `raspberry-pi-dramble` stack, and the network setup kept going haywire. No, the removal is not deliberate, and I need to get that file un-removed!

**Comment by geerlingguy** [comment]
Also... I can't figure out what's removing that file; I might reinstall Raspbian base and manually run everything to see if one of the package removals is ditching that file...

**Comment by geerlingguy** [comment]
Just found someone else mentioning that, if you remove the X window manager on Debian, and it was used previously to configure the networking setup, then the X removal can also damage/delete the `/etc/networking/interfaces` file.

Therefore, I think what I'll do is add a step to backup that file (maybe to `/tmp/network-interfaces`) prior to the apt package removal, then another step that restores it after the apt package removal is complete.
