### ISSUE TITLE
Creating an image will result in duplicate ssh host keys

### ISSUE THREAD

**Issue by erikoosterholm** [geerlingguy/diet-raspbian#8]
The instructions discuss creating a diet-pi image. Doing this will cause all hosts created with that image to use the same ssh host keys. One could automate changing the keys in the ansible playbook by deleting the existing host keys (/etc/ssh/ssh_host_key_) and then running dpkg-reconfigure openssl-server. Alternatively, the documentation should be modified to point out this issue when imaging multiple pis.

**Comment by geerlingguy** [comment]
Very true... I think documentation will be the best way to highlight this.

**Comment by geerlingguy** [comment]
Closing this issue, as I don't maintain this project anymore.
